# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-13 07:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_author_sex'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publisher',
            options={'ordering': ['name'], 'verbose_name': 'Chubanshe'},
        ),
    ]
